### ISSUE TITLE
FE -> make the Registration form

### ISSUE THREAD

**Issue by lanapavic** [Filip-Husic/fml_final_project_vue#6]
> REGISTRATION FORM MUST HAVE

- Name: ___________________
- Surname: ___________________
- Nickname: ___________________
- Age: ___________________
- E-mail: ___________________
- Password: ___________________ (MIN: 6 characters, 1 must be UpperCase , 1 LowerCase, 1 Number character, 1 special character)
- Password: ___________________ (for validation repeat password)

- BUTTON for "sign in" and BUTTON for "cancel" (if user chooses "Sign in" it redirects him to Login Form || goes back to Home page)

**Comment by Filip-Husic** [comment]
done
